export const REGISTRO_DENEGADO = 'REGISTRO_DENEGADO';
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';

export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_DENEGADO = 'LOGIN_DENEGADO';


export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';

export const CERRAR_SESION = 'CERRAR_SESION';
